{
 "title": "Speedtest",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Bandwidth",
   "type": "bargauge",
   "description": "Speedtest CLI Data ",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Download Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "exec_speedtest_input",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 120000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upload Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "exec_speedtest_input",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 120000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Resolution: www.stratuscube.com",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1.1.1.1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "1.1.1.1" },
      { "condition": "AND", "key": "domain", "operator": "=", "value": "www.stratuscube.com" }
     ]
    },
    {
     "alias": "8.8.8.8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "8.8.8.8" },
      { "condition": "AND", "key": "domain", "operator": "=", "value": "www.stratuscube.com" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "exec_speedtest_input",
     "select": [
      [
       { "params": [ "packetLoss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "exec_speedtest_input",
     "query": "SELECT first(\"download_bandwidth\") FROM \"exec_speedtest_input\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upload Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "exec_speedtest_input",
     "query": "SELECT first(\"upload_bandwidth\") FROM \"exec_speedtest_input\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Latency: www.stratuscube.com",
   "type": "graph",
   "description": "www.stratuscube.com",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "exec_speedtest_input",
     "select": [
      [
       { "params": [ "ping_latency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Jitter",
   "type": "graph",
   "description": "Jitter",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Ping Jitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "exec_speedtest_input",
     "select": [
      [
       { "params": [ "ping_jitter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Resolution Time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "alias": "ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  }
 ]
}